config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, except: [:new, :create] do
    get 'search', on: :collection
    resources :meetings, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :index, :show ] do
        get 'search', on: :collection
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :accepter, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: { message: 'Please give your first name' }
  has_many :requester_meetings, class_name: 'Meeting', foreign_key: 'requester_id', dependent: :destroy
  has_many :accepter_meetings, class_name: 'Meeting', foreign_key: 'accepter_id', dependent: :destroy
  has_many :availabilities, dependent: :destroy
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ActionController::API
      include Pundit

      after_action :verify_authorized, except: :index
      after_action :verify_policy_scoped, only: :index

      rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
      rescue_from ActiveRecord::RecordNotFound, with: :not_found

      private

      def user_not_authorized(exception)
        render json: {
          error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
        }, status: :unauthorized
      end

      def not_found(exception)
        render json: { error: exception.message }, status: :not_found
      end

      def matching_interests?(interests_user, interests_searcher)
        interests_searcher.select { |interest| interests_user.include?(interest) }
      end

      def available?(user, searcher)
        if searcher.availabilities.any? == false || user.availabilities.any? == false
          []
        else
          src_av_start = searcher.availabilities.map(&:start)
          src_av_end = searcher.availabilities.map(&:end)
          user.availabilities.select do |av|
            src_av_end.any? { |a| av.start < a } && src_av_start.any? { |s| av.end > s }
          end
        end
      end

      helper_method :matching_interests, :available
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::V1::BaseController
      acts_as_token_authentication_handler_for User, except: :index
      before_action :set_user, only: [:show]

      def index
        @users = policy_scope(User)
      end

      def show
        authorize @user
        @matching_interests = matching_interests?(@user.interests, current_user.interests)
        @matching_times = available?(@user, current_user)
      end

      def search
        @users = User.all
        authorize @users
        @matching_users = []
        @users.each do |user|
          if matching_interests?(user.interests, current_user.interests).length.positive? && available?(user, current_user).length.positive?
            @matching_users << user
          end
        end
        # authorize @matching_users
      end


      private

      def set_user
        @user = User.find(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_no interests])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone_no interests])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def matching_interests?(interests_user, interests_searcher)
    interests_searcher.select { |interest| interests_user.include?(interest) }
  end

  def available?(user, searcher)
    if searcher.availabilities.any? == false || user.availabilities.any? == false
      []
    else
      src_av_start = searcher.availabilities.map(&:start)
      src_av_end = searcher.availabilities.map(&:end)
      user.availabilities.select do |av|
        src_av_end.any? { |a| av.start < a } && src_av_start.any? { |s| av.end > s }
      end
    end
  end

  helper_method :matching_interests, :available
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  include Pundit

  def new
    @user = User.find(params[:user_id])
    @meeting = Meeting.new
    authorize @meeting
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @user = User.find(params[:user_id])
    @meeting.requester_id = current_user
    @meeting.accepter_id = @user
    authorize @meeting
    if @meeting.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def meeting_params
    params.require(:meeting).permit(:start, :end, :requester_id, :accepter_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Pundit

  skip_after_action :verify_authorized, only: [:home]

  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @users = policy_scope(User).order(first_name: :asc)
  end

  def search
    @users = User.all
    authorize @users
    @matching_users = []
    @users.each do |user|
      if matching_interests?(user.interests, current_user.interests).length.positive? && available?(user, current_user).length.positive?
        @matching_users << user
      end
    end
    # authorize @matching_users
  end

  def show
    authorize @user
    @matching_interests = matching_interests?(@user.interests, current_user.interests)
    @matching_times = available?(@user, current_user)
  end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<div class="container ml-3" >
  <h3>Call a meeting!</h3>
  <%= simple_form_for [@user, @meeting] do |f| %>
    <%= f.input :start, as: :string  %>
    <%= f.input :end, as: :string %>
    <%= f.submit class:'btn btn-primary'%>
  <% end %>
</div>

app/views/meetings/new.html.erb
<%= render "form", meeting: @meeting %>

app/views/pages/home.html.erb
<div class="container">
  <h1>Welcome to the user matching app</h1>
  <p>Sign up, tell us your interests and when you are available, and meet similar people!</p>
  <h3><%= link_to "Explore potential friends", users_path %> </h3>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "handshake.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "handshake.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li >
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign_up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="container text-center">
  <h1 style="margin-top: 5%;">Explore all our members</h1>
</div>

<div class="container text-center">
  <%= link_to "Filter by common interests and time availability that matches yours", search_users_path, class: "btn btn-primary border-radius-search-btn"  %>
</div>

<div class="ml-3 pl-3 mr-3 pr-3">
  <% @users.each do |user| %>
    <h3><%= link_to user.first_name, user_path(user) %></h3>
  <% end %>
</div>

app/views/users/search.html.erb
<div class="ml-3 pl-3 mr-3 pr-3">
  <% @matching_users.each do |user| %>
    <h3><%= link_to user.first_name, user_path(user) %> </h3>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.first_name %> <%= @user.last_name %> </h1>
  <p>Matching interests:</p>
  <%@matching_interests.each do |interest|  %>
  <p><%= interest %></p>
  <% end %>
  <p>Available to meet:</p>
  <% @matching_times.each do |time| %>
    <p> from <%= time.start %> to <%= time.end %> </p>
  <% end %>
  <%= link_to "Call a meeting", new_user_meeting_path(@user), class:'btn btn-primary' %>
</div>